config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :categories
  resources :portfolios, except: [:show]
  resources :jobs
  get 'facilitators', to: 'portfolios#facilitators'
  get 'training_managers', to: 'portfolios#training_managers'
  get 'equipment_managers', to: 'portfolios#equipment_managers'
  get 'event_managers', to: 'portfolios#event_manager'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

    
  
  get 'about', to: 'pages#about'
  get 'managers', to: 'pages#managers'
  get 'advertise', to: 'pages#advertise'
  get 'events', to: 'pages#events'
  get 'contact', to: 'pages#contact'
  
  get "concerns/new_contact" => 'concerns#new_contact', :as => :new_contact
    
   #get 'pages/trainers'
   #get 'pages/equipmentproviders'
   #get 'pages/eventmanagers'
   #get 'pages/facilitators'
  
  resources :posts do
    member do 
	    get :toggle_status
	  end
    end 	  

  root to: 'home#index' 
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :job
    
  include Placeholder
  validates_presence_of :title, :subtitle, :body, :contact, :job_id
  
  
  def self.facilitators
    where(subtitle: 'Facilitators')
  end
  
  def self.training_managers
    where(subtitle: 'Training Managers')
  end
  
  def self.equipment_managers
    where(subtitle: 'Equipment Managers')
  end
  
  def self.event_manager
    where(subtitle: 'Event Manager')
  end

  scope :event_manager_portfolios, -> { where(subtitle: 'Event Manager') }
  
   after_initialize :set_defaults

   def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
   before_action :set_portfolio, only: [:edit, :update, :show, :destroy]
    layout "portfolio"
	access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all 
  def index
    @portfolios = Portfolio.all
  end

  def angular
    @angular_portfolios = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
	@job = Job.all
end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  
  end

  def destroy
    # Destroy/delete the record
    @portfolio.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
									  :contact,
									  :job_id
									  )
  end
  
  def set_portfolio
  @portfolio = Portfolio.find(params[:id]) 
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :contact %>
    <%= f.text_field :contact %>
  </div>
  
  <div class="field">
    <%= f.label :job_id %>
    <%= f.text_field :job_id %>
  </div>
  
 <div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>

<p><%= portfolio.subtitle %></p>
  
<p><%= portfolio.body %></p>
  
<p><%= portfolio.contact %></p>
  
<%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>
<%= link_to 'Delete Portfolio', portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Managers Hub</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<%= render partial: 'portfolio', collection: @portfolios %>  

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>


 <%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<div class="post">
<%= image_tag @portfolio.main_image %>

<h1><%= @portfolio.title %></h1>

<em><%= @portfolio.subtitle %></em>

<p><%= @portfolio.body %></p>

<p><%= @portfolio.contact %></p>

</div>

app/views/portfolios/training_managers.html.erb
<h1>Training Managers Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @training_managers_portfolios.each do |portfolio_item| %>
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>
  <p><%= portfolio.subtitle %></p>
  <p><%= portfolio.body %></p>
  <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio) %>
  <%= link_to 'Delete Portfolio', portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>