config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :categories
  resources :portfolios, except: [:show]
  resources :jobs
  get 'facilitators', to: 'portfolios#facilitators'
  get 'training_managers', to: 'portfolios#training_managers'
  get 'equipment_managers', to: 'portfolios#equipment_managers'
  get 'event_managers', to: 'portfolios#event_manager'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

    
  
  get 'about', to: 'pages#about'
  get 'managers', to: 'pages#managers'
  get 'advertise', to: 'pages#advertise'
  get 'events', to: 'pages#events'
  get 'contact', to: 'pages#contact'
  
  get "concerns/new_contact" => 'concerns#new_contact', :as => :new_contact
    
   #get 'pages/trainers'
   #get 'pages/equipmentproviders'
   #get 'pages/eventmanagers'
   #get 'pages/facilitators'
  
  resources :posts do
    member do 
	    get :toggle_status
	  end
    end 	  

  root to: 'home#index' 
end

app/views/shared/_application_footer.html.erb
<div id="footer">
   	  <p><%= copyright_generator %></p>
</div>
	

app/views/shared/_application_nav.html.erb
<nav id="menu" class="nav nav-masthead">
            <li><%= link_to "Home", root_path, class: 'nav-link' %></li>
			<li><%= link_to "About", about_path, class: 'nav-link' %></li>
			<li><%= link_to "Post",posts_path, class: 'nav-link' %></li>
			<li><%= link_to "Managers", portfolios_path, class: 'nav-link' %></li>
			<li><%= link_to "Events", events_path, class: 'nav-link' %></li>
			<li><%= link_to "Advertise", advertise_path, class: 'nav-link' %></li>
			<li><%= link_to "Contact",contact_path, class: 'nav-link' %></li>
			<%= login_helper 'nav-link' %> 
</nav>

app/views/shared/_header_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
    <title><%= @page_title %></title>
	
		
	<link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
   	<meta name="keywords" content="<%= @seo_keywords %>" />
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
	 
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">Global Platform for Engineering</a></h1>
			</div>
		        <nav id="menu" class="nav nav-masthead">
                   <%= link_to "Home", root_path, class: 'nav-link' %>
			       <%= link_to "About", about_path, class: 'nav-link' %>
			       <%= link_to "Managers", portfolios_path,class: 'nav-link'  %>
			       <%= link_to "Events", events_path, class: 'nav-link' %>
			       <%= link_to "Advertise", advertise_path, class: 'nav-link' %>
			       <%= link_to "Contact",contact_path, class: 'nav-link' %>
			       <%= login_helper 'nav-link' %>
              </nav>
			</div>
	  </div>
 </div>
	<!-- end #header -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
	  <div><%= link_to "Engineering Post",posts_path %></div>
      <div><%= link_to "Managers", portfolios_path %></div>
      <div><%= link_to "Event", event_path %></div>
</div>

<div class="<%= location %>">
      <div><%= link_to "Advertise", advertise_path %></div
      <div><%= link_to "Contact",contact_path %></div>
</div>

app/views/shared/_new_contact.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Interested Contact Us</h3>
 </div>
 <div class="modal-body">
   <br>
      <div id="container">  
        <form method="post" action="process.php">
		<ul>
		  <li>
			 <label>First Name: </label>
			<input name="first_name" type="text">
			 <br/>
			 <br/>
			 <label>Last Name: </label>
			 <input name="last_name" type="text">
			  <br/>
			  <br/>
				<label>Email: </label>
				<input name="email" type="email" />
				<br />
				<br/>
					
				<label>Gender: </label>
				<input type="radio" name="gender" value="Male" />Male
				&nbsp; 
				<input type="radio" name="gender" value="Female" />Female
				<br/>
				<br/>
				<label>Message: </label>
				<textarea name="message"></textarea>
				<br /><br />
				<input type="submit" value="Submit" />
				</li>
				</ul>
				 </form>
                </div>
 </div>
 <div class="modal-footer">
   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   <button class="btn btn-primary">Save changes</button>
 </div>

app/views/shared/_sidebar_nav.html.erb
<div id="sidebar">
					<ul>
						<li>
							<div id="search" >
								<form method="get" action="#">
									<div>
										<input type="text" name="s" id="search-text" value="" />
										<input type="submit" id="search-submit" value="GO" />
									</div>
								</form>
							</div>
							<div style="clear: both;">&nbsp;</div>
						</li>
						<li>
							<h2>Categories</h2>
							<ul>
								<% all_categories.each do |cat| %>
									<li><%= link_to cat.name,category_path(:id => cat.id) %></li>
								<% end %>
					
							</ul>
						</li>
				</ul>
		</div>
				<!-- end #sidebar -->