config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :categories
  resources :portfolios, except: [:show]
  resources :jobs
  get 'facilitators', to: 'portfolios#facilitators'
  get 'training_managers', to: 'portfolios#training_managers'
  get 'equipment_managers', to: 'portfolios#equipment_managers'
  get 'event_managers', to: 'portfolios#event_manager'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

    
  
  get 'about', to: 'pages#about'
  get 'managers', to: 'pages#managers'
  get 'advertise', to: 'pages#advertise'
  get 'events', to: 'pages#events'
  get 'contact', to: 'pages#contact'
  
  get "concerns/new_contact" => 'concerns#new_contact', :as => :new_contact
    
   #get 'pages/trainers'
   #get 'pages/equipmentproviders'
   #get 'pages/eventmanagers'
   #get 'pages/facilitators'
  
  resources :posts do
    member do 
	    get :toggle_status
	  end
    end 	  

  root to: 'home#index' 
end

app/models/post.rb
class Post < ApplicationRecord
     enum status: {draft: 0, published: 1 }
		
	extend FriendlyId
    friendly_id :theme, use: :slugged
	
	
	
	
	include Placeholder 
	validates_presence_of :theme, :body, :timings, :fees, :footfall, :editions, :organizer, :venue, :category_id, :period
	belongs_to :category
	
	def self.special_posts
	  all
	end
	
    #def self.featured_posts
    #  limit(2)
    #end
  
  after_initialize :set_defaults
  
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '300')
 end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "post" 
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all 
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.special_posts
	@page_title = "Engineering Posts"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @page_title = @post.theme
	 @seo_keywords = @post.body
  end

  # GET /posts/new
  def new
    @post = Post.new
	@category = Category.all
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
     else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
     else
        format.html { render :edit }
     end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
 def toggle_status
    if @post.draft?
      @post.published!
    elsif @post.published?
      @post.draft!
    end
        
    redirect_to posts_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:theme, :body, :timings, :fees, :footfall, :editions, :organizer, :venue, :category_id, :contact, :period) 
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :theme %>
    <%= form.text_field :theme, id: :post_theme, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body, class: 'form-control', rows:15 %>
  </div>
                                                        
  <div class="form-group">                                  
    <%= form.label :timings %>
    <%= form.text_area :timings, id: :post_timings, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :fees %>
    <%= form.text_area :fees, id: :post_fees, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :footfall %>
    <%= form.text_area :footfall, id: :post_footfall, class: 'form-control' %>
  </div>
  
  
  <div class="form-group">
    <%= form.label :editions %>
    <%= form.text_area :editions, id: :post_editions, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :contact %>
    <%= form.text_area :contact, id: :post_contact, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :organizer %>
    <%= form.text_area :organizer, id: :post_organizer, class: 'form-control' %>
  </div> 

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_area :venue, id: :post_venue, class: 'form-control' %>
  </div> 
  
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :post_category_id, class: 'form-control' %>
  </div> 
  
 <div class="form-group">
    <%= form.label :period %>
    <%= form.text_area :period, id: :post_period, class: 'form-control' %>
  </div> 
  

 
   <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <h2 class="post-theme"><%= link_to post.theme.upcase, post %></h2>
  <p class="meta">Published <%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>
  
  <% if logged_in?(:site_admin) %>
    <p class="meta">
    <%= link_to post.status, toggle_status_post_path(post) %> /
    <%= link_to 'Edit', edit_post_path(post) if logged_in?(:site_admin) %> /
    <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
    </p>
  <% end %>

  <p>
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="col-sm-8 post-main">

    <h1>Editing Post</h1>

      <%= render 'form', post: @post %>
       @categories = Category.all

      <%= link_to 'Show', @post if logged_in?(:site_admin) %> |
      <%= link_to 'Back', posts_path if logged_in?(:site_admin) %>

</div>

app/views/posts/index.html.erb
<div class="col-sm-8 post-main">

    <%= render @posts %>

  <nav class="post-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
  </nav>

</div>

app/views/posts/new.html.erb
 <div class="col-sm-8 post-main"> 
  
  <h1>New Post</h1>

   <%= render 'form', post: @post %>

     <%= link_to 'Back', posts_path if logged_in?(:site_admin) %>

</div>

app/views/posts/new_contact.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'application/modal') %>");
$("#modal-window").modal();

app/views/posts/show.html.erb
<div class="card bg-dark text-white">
 <%= image_tag @post.main_image %>
  <div class="card-img-overlay">
  <h2 class="card-title"><%= @post.theme %></h2>
  <ul>
  <li>
   <span class="glyphicon glyphicon-map-marker"><h5 class="card-title"><%= @post.period %></h5></span>
  
   
  </li>
  <li>
  <h5 class="card-title"><%= @post.venue %></h5>
  </li>
  </ul>
  </div>
</div>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<hr>


<div class="card text-center">
  <div class="card-header">Featured</div>
     <div class="card-group">
       <div class="card border-light mb-3" style="max-width: 30rem;">
         <div class="card-header">FEES</div>
           <div class="card-body">
		    <p class="card-text" align =center><%= @post.fees %></p>
          </div>
         </div>
		 <hr>
          <div class="card border-light mb-3" style="max-width: 30rem;">
          <div class="card-header" align=center>TIMINGS</div>
             <div class="card-body">
             <p class="card-text" align =center><%= @post.timings %></p>
          </div>
         </div>
		 <hr>
		 <div class="card border-light mb-3" style="max-width: 30rem;">
          <div class="card-header" align=center>FOOTFALL</div>
             <div class="card-body">
              <p class="card-text" align =center><%= @post.footfall %></p>
          </div>
         </div>
		 </div>
        <div class="card-footer text-muted">
    </div>
</div>
  <hr>
 
 <div class="card text-center">
  <div class="card-header">Featured</div>
     <div class="card-group">
       <div class="card border-light mb-3" style="max-width: 30rem;">
         <div class="card-header">EDITIONS</div>
           <div class="card-body">
             <p class="card-text" align =center><%= @post.editions %></p>
          </div>
         </div>
		 <hr>
          <div class="card border-light mb-3" style="max-width: 30rem;">
          <div class="card-header" align=center>CONTACT</div>
             <div class="card-body">
             <p class="card-text" align =center><%= @post.contact %></p>
          </div>
         </div>
		 <hr>
		 <div class="card border-light mb-3" style="max-width: 30rem;">
          <div class="card-header" align=center>ORGANIZER</div>
             <div class="card-body">
              <p class="card-text" align =center><%= @post.organizer %></p>
          </div>
         </div>
		 </div>
        <div class="card-footer text-muted">
     </div>
  </div>	

   
<%= link_to 'Edit', edit_post_path(@post) if logged_in?(:site_admin) %> |

 <%= link_to '<button type="button">New Post</button>'.html_safe, new_post_path if logged_in?(:site_admin) %>
 